spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MINE
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': false
        '[naming.physical-strategy]': org.hibernate.boot.model.naming.SpringPhysicalNamingStrategy

  thymeleaf:
    cache: false

logging:
  level:
    root: info
    # '[org.thymeleaf.TemplateEngine]': info
    # '[org.springframework.boot.autoconfigure.logging]': info
    # '[org.apache.coyote.http11.Http11InputBuffer]': debug
    # '[org.springframework.security]': debug
